apiVersion: v1
description: Kibana analytics and search dashboard for Elasticsearch
maintainers:
- email: abrand@apprenda.com
  name: Alexander Brand
- email: dkoshkin@apprenda.com
  name: Dimitri Koshkin
name: kibana
version: 0.1.0
