## Kibana container image
## 
image: blacktop/kibana:5.4

namespace: default

## Number of replicas to be deployed
## 
replicas: 1

## Kubernetes service type for the Kibana dashboard
## 
serviceType: LoadBalancer

## Elasticsearch configuration
## 
elasticsearch:
  ## The host or IP of the elasticsearch cluster
  ##
  # host:
  ## The port to be used for connecting to the elasticsearch cluster
  ## 
  port: 9200

## Configure resource requests and limits
## see: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 100m
  requests:
    cpu: 100m

ingress:
  hostname: kibana.example.com